# -*- coding: utf-8 -*-
"""P-114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exqy3eHVt4m9-6P8FFBTv5QhqodQA8h6
"""

from google.colab import files
files=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv('data.csv')
toefl=df['TOEFL Score'].tolist()
chances_of_admit=df['Chance of Admit '].tolist()
fig=px.scatter(x=toefl,y=chances_of_admit)
fig.show()

import numpy as np
toefl_score_array=np.array(toefl)
chances_of_admit_array=np.array(chances_of_admit)
m,c=np.polyfit(toefl_score_array,chances_of_admit_array,1)
y=[]
for x in toefl_score_array:
  y_value=m*x+c
  y.append(y_value)
fig=px.scatter(x=toefl_score_array,y=chances_of_admit_array)
fig.update_layout(shapes=[
    dict(type='line',
        y0=min(y),
        y1=max(y),
        x0=min(toefl_score_array),
        x1=max(toefl_score_array)),
])
fig.show()